// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyte8nyyEgQTwAPd7YyRFcz57qeC-lGJQ',
    appId: '1:1015771432536:web:a3a6d3ed11f0598aad6c2d',
    messagingSenderId: '1015771432536',
    projectId: 'occazcar-65305',
    authDomain: 'occazcar-65305.firebaseapp.com',
    storageBucket: 'occazcar-65305.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqsxxTbI3F3FYICXS2Nefgs0K21s-fs68',
    appId: '1:1015771432536:android:6e2ea4d4e20498d8ad6c2d',
    messagingSenderId: '1015771432536',
    projectId: 'occazcar-65305',
    storageBucket: 'occazcar-65305.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyte8nyyEgQTwAPd7YyRFcz57qeC-lGJQ',
    appId: '1:1015771432536:web:e30f26287aa4977ead6c2d',
    messagingSenderId: '1015771432536',
    projectId: 'occazcar-65305',
    authDomain: 'occazcar-65305.firebaseapp.com',
    storageBucket: 'occazcar-65305.firebasestorage.app',
  );
}
